#!/usr/bin/env python3
"""Unified multi-toolchain generator and synchronizer for the Photo Selector Toolbox AI framework.

Generates and synchronizes all downstream AI toolchains from canonical sources in ai/:
  - Cursor: .cursor/rules/*.mdc, .cursorrules
  - Windsurf: .windsurfrules
  - GitHub Copilot: .github/copilot-instructions.md
  - Gemini CLI: .gemini/settings.json, .gemini/agents/, .gemini/skills/
  - Claude Code: .claude/
  - Antigravity: .agents/
  - Root: ROUTING.md

Supports two synchronization modes:
  - symlink: Creates relative symlinks to canonical ai/ files (default when supported).
  - copy: Copies canonical files with read-only permissions (0o444) and persists .sync_mode.

Usage:
    python3 ai/skills/sync-framework/scripts/sync_framework.py                # auto-detect mode & sync
    python3 ai/skills/sync-framework/scripts/sync_framework.py --mode=copy    # force copy mode
    python3 ai/skills/sync-framework/scripts/sync_framework.py --copy         # alias for --mode=copy
    python3 ai/skills/sync-framework/scripts/sync_framework.py --mode=symlink # force symlinks
    python3 ai/skills/sync-framework/scripts/sync_framework.py --check        # verify sync state
    python3 ai/skills/sync-framework/scripts/sync_framework.py --clean        # purge obsolete files
    python3 ai/skills/sync-framework/scripts/sync_framework.py -v             # verbose output
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import filecmp
import json
import os
from pathlib import Path
import shutil
import stat
import sys
from typing import Any

REPO = Path(__file__).resolve().parents[4]
AI = REPO / "ai"
AGENTS = AI / "agents"
SKILLS = AI / "skills"
RULES = AI / "rules"
COMMANDS = AI / "commands"
ROUTING = AI / "ROUTING.md"
SYNC_MODE_FILE = REPO / ".sync_mode"

GENERATION_BANNER = (
    "<!-- DO NOT HAND EDIT: Generated by ai/skills/sync-framework/scripts/sync_framework.py -->\n"
    "<!-- Canonical source of truth lives in ai/ (ai/agents/, ai/skills/, ai/rules/, ai/ROUTING.md) -->\n"
)

# Directory mappings: Target relative to REPO -> Source relative to REPO
DIR_MAPPINGS = {
    ".claude/agents": "ai/agents",
    ".claude/skills": "ai/skills",
    ".claude/hooks": "ai/hooks",
    ".claude/commands": "ai/commands",
    ".agents/skills": "ai/skills",
    ".agents/workflows": "ai/commands",
    ".agents/rules": "ai/rules",
}

# Single-file mappings: Target relative to REPO -> Source relative to REPO
FILE_MAPPINGS = {
    "ROUTING.md": "ai/ROUTING.md",
}

DO_NOT_EDIT_BANNER = """# DO NOT EDIT THIS DIRECTORY

This directory contains mirrored files generated from `ai/` by `sync_framework.py`.
Current synchronization mode: **COPY** (non-symlink fallback).

All mirrored files in this directory are read-only copies.
Any direct modifications will be overwritten during the next framework synchronization.

### How to make changes:
1. Edit the canonical source file under `ai/`.
2. Run synchronization to update mirrors:
   ```bash
   python3 ai/skills/sync-framework/scripts/sync_framework.py
   python3 ai/skills/sync-framework/scripts/validate_framework.py
   ```
"""


def make_writable(path: Path) -> None:
    """Grant user write permission on a path if it exists."""
    if path.exists() or os.path.lexists(path):
        try:
            if path.is_dir() and not path.is_symlink():
                os.chmod(path, stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO)
            else:
                os.chmod(path, stat.S_IWUSR | stat.S_IRUSR | stat.S_IWGRP | stat.S_IRGRP | stat.S_IROTH)
        except OSError:
            pass


def make_readonly(path: Path) -> None:
    """Grant read-only permission (0o444 on POSIX, S_IREAD on Windows)."""
    if path.exists():
        try:
            if path.is_dir() and not path.is_symlink():
                os.chmod(path, stat.S_IRUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
            else:
                os.chmod(path, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
        except OSError:
            pass


def remove_path(path: Path) -> None:
    """Safely remove a file, symlink, or directory tree handling read-only bits."""
    if not (path.exists() or path.is_symlink() or os.path.lexists(path)):
        return
    if path.is_symlink() or path.is_file():
        make_writable(path)
        path.unlink(missing_ok=True)
    elif path.is_dir():
        def _ensure_dir_writable(p):
            try:
                os.chmod(p, stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO)
            except OSError:
                pass

        _ensure_dir_writable(path)
        for root, dirs, files in os.walk(path):
            for d in dirs:
                _ensure_dir_writable(Path(root) / d)
            for f in files:
                try:
                    os.chmod(Path(root) / f, stat.S_IWUSR | stat.S_IRUSR)
                except OSError:
                    pass

        def _on_err(func, p, exc_info):
            try:
                _ensure_dir_writable(p)
                func(p)
            except OSError:
                pass

        if sys.version_info >= (3, 12):
            def _on_exc(func, p, exc):
                try:
                    _ensure_dir_writable(p)
                    func(p)
                except OSError:
                    pass
            shutil.rmtree(path, onexc=_on_exc)
        else:
            shutil.rmtree(path, onerror=_on_err)


def probe_symlink_capability(repo_dir: Path) -> bool:
    """Probe whether symlinks can be created in this environment."""
    probe_dir = repo_dir / ".gemini"
    probe_dir.mkdir(parents=True, exist_ok=True)
    probe_link = probe_dir / ".probe_symlink"
    try:
        if probe_link.is_symlink() or probe_link.exists():
            probe_link.unlink(missing_ok=True)
        os.symlink("settings.json", probe_link)
        resolves = probe_link.exists() or probe_link.is_symlink()
        probe_link.unlink(missing_ok=True)
        return bool(resolves)
    except (OSError, NotImplementedError):
        try:
            if probe_link.is_symlink() or probe_link.exists():
                probe_link.unlink(missing_ok=True)
        except OSError:
            pass
        return False


def get_current_sync_mode() -> str:
    """Return stored sync mode from .sync_mode, or default based on primary mirror."""
    if SYNC_MODE_FILE.exists():
        try:
            data = json.loads(SYNC_MODE_FILE.read_text(encoding="utf-8"))
            return data.get("mode", "symlink")
        except Exception:
            pass
    primary = REPO / ".claude" / "agents"
    return "symlink" if primary.is_symlink() else "copy"


# ── Frontmatter and Data Extractors ───────────────────────────────────────────

def parse_frontmatter(path: Path) -> dict[str, str]:
    """Extract flat key: value YAML frontmatter without external dependencies."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = text.find("\n---\n", 3)
    if end == -1:
        raise ValueError(f"{path}: unterminated YAML frontmatter")

    fields: dict[str, str] = {}
    for line in text[4:end].split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[0].isspace() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fields[key.strip()] = value
    return fields


def load_agents() -> list[dict[str, Any]]:
    agents = []
    for p in sorted(AGENTS.glob("*.md")):
        fm = parse_frontmatter(p)
        agents.append({
            "name": fm.get("name", p.stem),
            "description": fm.get("description", ""),
            "tools": fm.get("tools", ""),
            "model": fm.get("model", "inherit"),
            "path": p,
        })
    return agents


def load_skills() -> list[dict[str, Any]]:
    skills = []
    for d in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        sf = d / "SKILL.md"
        if sf.exists():
            fm = parse_frontmatter(sf)
            skills.append({
                "name": fm.get("name", d.name),
                "description": fm.get("description", ""),
                "tools": fm.get("allowed-tools", ""),
                "path": sf,
            })
    return skills


PRODUCTS = [
    {
        "id": "desktop",
        "name": "Desktop",
        "path": "products/desktop",
        "globs": "products/desktop/**/*",
        "tech": "Python 3.11+, Tkinter, Poetry, Pytest",
        "target": "macOS, Linux, Windows workstations",
        "doc": "docs/products/desktop/REQUIREMENTS.md",
        "agents": [
            ("products/desktop/src/photo_selector_toolbox/{core,exif,tools}/, cli.py", "@desktop-backend-agent"),
            ("products/desktop/src/photo_selector_toolbox/gui/", "@desktop-gui-agent"),
            ("products/desktop/tests/, products/desktop/benchmarks/", "@desktop-test-agent"),
            ("products/desktop/scripts/, pyproject.toml, poetry.lock", "@desktop-build-agent"),
        ],
        "test_cmd": "poetry run pytest products/desktop/tests/unit -m \"not visual\"",
        "notes": "Never update Tkinter widgets from background worker threads. Asynchronous EXIF reading and thumbnail caching via thread pools.",
    },
    {
        "id": "macos-desktop",
        "name": "Native macOS Desktop",
        "path": "products/macos-desktop",
        "globs": "products/macos-desktop/**/*",
        "tech": "Swift 6, SwiftUI, Apple Vision, Apple Accelerate, ImageIO",
        "target": "macOS 14+ / macOS 15+ Apple Silicon & Intel workstations",
        "doc": "docs/products/macos-desktop/REQUIREMENTS.md",
        "agents": [
            ("products/macos-desktop/", "@macos-desktop-agent"),
        ],
        "test_cmd": "swift test --package-path products/macos-desktop",
        "notes": "Apple Human Interface Guidelines, on-device Apple Vision aesthetic scoring, Accelerate Laplacian focus evaluation, ImageIO transform decode, native Settings (⌘,), zero Python/server dependencies.",
    },
    {
        "id": "android-desktop",
        "name": "Android Desktop (:android-desktop)",
        "path": "products/android/android-desktop",
        "globs": "products/android/android-desktop/**/*",
        "tech": "Kotlin, Jetpack Compose, Room, OpenCV, Vico",
        "target": "Samsung DeX, Android tablets >= 840 dp, Chromebooks",
        "doc": "docs/products/android-desktop/REQUIREMENTS.md",
        "agents": [
            ("products/android/android-desktop/src/com/photoselectortoolbox/{ui,viewmodel}/", "@android-desktop-ui-agent"),
            ("products/android/android-desktop/src/com/photoselectortoolbox/{data,domain,di}/", "@android-desktop-core-agent"),
            ("products/android/ (build, gradle)", "@android-shared-build-agent"),
        ],
        "test_cmd": "./gradlew :products:android:android-desktop:testDebugUnitTest",
        "notes": "Multi-window and Samsung DeX support. Adapts to freeform resizing. Uses :core for EXIF models.",
    },
    {
        "id": "phototok",
        "name": "PhotoTok (:phototok)",
        "path": "products/android/phototok",
        "globs": "products/android/phototok/**/*",
        "tech": "Kotlin, Jetpack Compose, DataStore, SAF",
        "target": "Android phones < 600 dp, portrait, gesture-first navigation",
        "doc": "docs/products/phototok/REQUIREMENTS.md",
        "agents": [
            ("products/android/phototok/src/com/phototok/{ui,viewmodel}/", "@phototok-ui-agent"),
            ("products/android/phototok/src/com/phototok/{data,domain,di}/", "@phototok-core-agent"),
            ("products/android/ (build, gradle)", "@android-shared-build-agent"),
        ],
        "test_cmd": "./gradlew :products:android:phototok:testDebugUnitTest",
        "notes": "Single-handed mobile ergonomics. Fullscreen vertical feed with swipe-to-cull gestures. Destructive action undo/confirmation windows.",
    },
    {
        "id": "android-core",
        "name": "Shared Android Core (:core)",
        "path": "products/android/core",
        "globs": "products/android/core/**/*",
        "tech": "Kotlin, EXIF data model & reader interfaces",
        "target": "Shared between :android-desktop and :phototok",
        "doc": "products/android/core/build.gradle.kts",
        "agents": [
            ("products/android/core/", "@android-desktop-core-agent & @phototok-core-agent (dual review)"),
        ],
        "test_cmd": "./gradlew :products:android:core:testDebugUnitTest",
        "notes": "Strict admission rule: Only code identical for both products that stays identical if either evolves independently. No UI code.",
    },
    {
        "id": "linux-desktop",
        "name": "Linux Desktop",
        "path": "products/linux-desktop",
        "globs": "products/linux-desktop/**/*",
        "tech": "Python 3.11+, PyGObject, GTK4, Libadwaita, GExiv2 / PIL",
        "target": "Debian 13 (Trixie), GNOME 46+ workstations",
        "doc": "docs/products/linux-desktop/REQUIREMENTS.md",
        "agents": [
            ("products/linux-desktop/", "@linux-desktop-agent"),
        ],
        "test_cmd": "pytest products/linux-desktop/tests/",
        "notes": "GNOME Human Interface Guidelines, AdwHeaderBar, dark studio styling, FreeDesktop Gio.File.trash, Debian 13 APT packaging.",
    },
]

CONSULTANTS = [
    ("@shared-photo-researcher-agent", "Photographic science, optical formulas, EXIF APEX standards (Tv, Av, Sv), sharpness metrics, color science."),
    ("@shared-ux-agent", "Multi-device ergonomics, Nielsen Norman heuristics, touch targets, contrast (WCAG >= 4.5:1), keyboard navigation."),
    ("@shared-publish-agent", "Google Play policies, OAuth scopes (drive.file only), privacy policies, DSGVO/GDPR, German DDG/Impressum."),
    ("@shared-code-health-agent", "Architectural refactoring, tech debt remediation, framework maintenance, dead code removal."),
    ("@shared-mentor-agent", "Mandatory gate before writing to ai/memory/ (record-lesson), playbook creation (create-playbook)."),
]


# ── Toolchain Generators ──────────────────────────────────────────────────────

def build_cursor_always_on() -> str:
    return (
        "---\n"
        "description: \"Non-negotiable repository rules, product boundaries, task lifecycle, and test verification\"\n"
        "globs: \"\"\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{GENERATION_BANNER}\n"
        "# Photo Selector Toolbox — Global Repository Rules\n\n"
        "## The Five Products\n"
        "This repository ships **five independent products** sharing photographic concepts (EXIF contract, score semantics, Selection folder convention) and nothing else:\n"
        "1. **Desktop** (`products/desktop/`) — Python + Tkinter\n"
        "2. **Android Desktop** (`products/android/android-desktop/`) — Kotlin + Compose (Samsung DeX, tablets >= 840 dp)\n"
        "3. **PhotoTok** (`products/android/phototok/`) — Kotlin + Compose (Phones < 600 dp, gesture-first)\n"
        "4. **Native macOS Desktop** (`products/macos-desktop/`) — Swift 6 + SwiftUI (macOS 14+/15+)\n"
        "5. **Linux Desktop** (`products/linux-desktop/`) — Python + PyGObject + GTK4 + Libadwaita (Debian 13, GNOME 46+)\n\n"
        "Shared code is strictly isolated: `products/android/core/` is the ONLY shared code between Android products.\n"
        "**Never copy or leak code between products. Cross-product code leakage is a defect.**\n\n"
        "## Non-Negotiable Workflow Rules\n"
        "1. **Identify product first:** Determine which product a task targets before opening files.\n"
        "2. **Mandatory task lifecycle:**\n"
        "   - Pre-work: Read `ai/skills/task-lifecycle/SKILL.md`, target product `REQUIREMENTS.md`, and matching `ai/memory/` lessons.\n"
        "   - Post-work: Execute `ai/skills/retrospective/SKILL.md`, sync `REQUIREMENTS.md` if behavior changed, and consult mentor before memory updates.\n"
        "3. **Verify against CI mirror:** Always run `./scripts/run_tests.sh` (or `./scripts/run_tests.sh --all`). Never rely on partial test subsets.\n"
        "4. **No scratch files:** Never commit scratch scripts, temporary debug dumps, or PR description files.\n"
        "5. **Single source of truth:** All framework definitions live under `ai/`. Never edit generated files directly.\n"
    )


def build_cursor_product_rule(prod: dict[str, Any]) -> str:
    agents_table = "\n".join(f"- `{path}`: {agent}" for path, agent in prod["agents"])
    return (
        "---\n"
        f"description: \"Architecture, standards, and testing for {prod['name']}\"\n"
        f"globs: \"{prod['globs']}\"\n"
        "alwaysApply: false\n"
        "---\n\n"
        f"{GENERATION_BANNER}\n"
        f"# {prod['name']}\n\n"
        "## Overview\n"
        f"- **Path**: `{prod['path']}`\n"
        f"- **Tech Stack**: {prod['tech']}\n"
        f"- **Target Platforms**: {prod['target']}\n"
        f"- **Documentation**: `{prod['doc']}`\n\n"
        "## Component Ownership\n"
        f"{agents_table}\n\n"
        "## Test & Verification Commands\n"
        f"- Primary test: `{prod['test_cmd']}`\n"
        "- CI mirror: `./scripts/run_tests.sh`\n\n"
        "## Architectural Invariants\n"
        f"{prod['notes']}\n"
        "- **Strict Isolation**: Do not import from or copy code to other products.\n"
    )


def build_cursor_consultants() -> str:
    rows = "\n".join(f"| {agent} | {desc} |" for agent, desc in CONSULTANTS)
    return (
        "---\n"
        "description: \"Roster of cross-product specialist consultants: photo researcher, UX, publish, code health, mentor\"\n"
        "globs: \"\"\n"
        "alwaysApply: false\n"
        "---\n\n"
        f"{GENERATION_BANNER}\n"
        "# Cross-Product Specialist Consultants\n\n"
        "| Consultant Agent | Role & Domain Authority |\n"
        "|---|---|\n"
        f"{rows}\n"
    )


def build_cursorrules() -> str:
    return (
        f"{GENERATION_BANNER}\n"
        "# Cursor Rules — Photo Selector Toolbox\n\n"
        "## The Five Products\n"
        "- Desktop (`products/desktop/`): Python + Tkinter\n"
        "- Android Desktop (`products/android/android-desktop/`): Kotlin + Compose (DeX/tablets)\n"
        "- PhotoTok (`products/android/phototok/`): Kotlin + Compose (phones < 600 dp)\n"
        "- Native macOS Desktop (`products/macos-desktop/`): Swift 6 + SwiftUI\n"
        "- Linux Desktop (`products/linux-desktop/`): Python + GTK4 + Libadwaita\n\n"
        "## Core Invariants\n"
        "1. Identify product first; never leak code across products.\n"
        "2. Start with `task-lifecycle` skill; end with `retrospective` skill.\n"
        "3. Verify against local CI mirror: `./scripts/run_tests.sh`.\n"
        "4. No scratch files in repository.\n"
        "5. Canonical framework source is `ai/`.\n"
    )


def build_windsurfrules(skills: list[dict[str, Any]]) -> str:
    prod_table = "\n".join(
        f"| **{p['name']}** | `{p['path']}` | {p['tech']} | {p['target']} | `{p['test_cmd']}` |"
        for p in PRODUCTS
    )
    skill_table = "\n".join(
        f"| `{s['name']}` | {s['description']} |"
        for s in skills
    )
    consult_table = "\n".join(
        f"| `{agent}` | {desc} |"
        for agent, desc in CONSULTANTS
    )
    return (
        f"{GENERATION_BANNER}\n"
        "# Windsurf Rules — Photo Selector Toolbox\n\n"
        "## 1. Repository Architecture & The Five Products\n"
        "This repository ships **five independent products** sharing photographic concepts (EXIF contract, score semantics, Selection folder convention) and nothing else:\n\n"
        "| Product | Code Path | Tech Stack | Target Platform | Test Command |\n"
        "|---|---|---|---|---|\n"
        f"{prod_table}\n\n"
        "## 2. Non-Negotiable Invariants\n"
        "- **Strict Product Isolation**: Never import or copy code between products. `products/android/core/` is the ONLY shared code between Android products.\n"
        "- **Mandatory Task Lifecycle**: Always start with `ai/skills/task-lifecycle/SKILL.md` (read product REQUIREMENTS.md and ai/memory/ lessons) and conclude with `ai/skills/retrospective/SKILL.md`.\n"
        "- **Comprehensive Verification**: Verify every change with `./scripts/run_tests.sh`. Never rely on partial test subsets.\n"
        "- **Zero Code Review Standard**: Ensure all deliveries are accompanied by verifiable test results and requirement sync.\n"
        "- **Clean Workspace Hygiene**: Never commit scratch files (`scratch*.py`, temporary logs, PR drafts).\n"
        "- **Canonical Framework**: All configuration lives in `ai/`. Never hand-edit generated toolchain files.\n\n"
        "## 3. Cross-Product Specialist Consultants\n"
        "| Agent | Authority & Scope |\n"
        "|---|---|\n"
        f"{consult_table}\n\n"
        "## 4. Shared Skills & Workflow Triggers\n"
        "| Skill | Trigger & Description |\n"
        "|---|---|\n"
        f"{skill_table}\n"
    )


def build_copilot_instructions() -> str:
    prod_table = "\n".join(
        f"- **{p['name']}** (`{p['path']}`): {p['tech']}. Target: {p['target']}. Test: `{p['test_cmd']}`."
        for p in PRODUCTS
    )
    return (
        f"{GENERATION_BANNER}\n"
        "# GitHub Copilot Instructions — Photo Selector Toolbox\n\n"
        "## Repository Overview\n"
        "This repository ships five independent photo culling products that share photographic concepts (EXIF contract, score semantics, Selection workflow) but maintain independent implementations:\n"
        f"{prod_table}\n\n"
        "## Mandatory Architectural Invariants\n"
        "1. **Product Isolation**: Never leak code between products. Copying files between products is a defect.\n"
        "2. **Shared Android Core**: `products/android/core/` (`:core`) is the ONLY shared code between Android products. Admission requires identical behavior and dual-agent review.\n"
        "3. **Task Lifecycle**: Pre-work requires reading `docs/products/<product>/REQUIREMENTS.md` and `ai/memory/`. Post-work requires test execution and updating requirements to reflect observable behavior.\n"
        "4. **Verification**: Verify against `./scripts/run_tests.sh`, which mirrors all CI gates.\n"
        "5. **Hygiene**: No scratch files or debug dumps in repository.\n"
        "6. **Single Source of Truth**: Canonical framework lives in `ai/`. Never hand-edit `.github/copilot-instructions.md`, `.cursor/`, `.windsurfrules`, or `.gemini/`.\n\n"
        "## Product Testing Reference\n"
        "- Desktop: `poetry run pytest products/desktop/tests/unit -m \"not visual\"`\n"
        "- macOS Desktop: `swift test --package-path products/macos-desktop`\n"
        "- Android Desktop: `./gradlew :products:android:android-desktop:testDebugUnitTest`\n"
        "- PhotoTok: `./gradlew :products:android:phototok:testDebugUnitTest`\n"
        "- Linux Desktop: `pytest products/linux-desktop/tests/`\n"
        "- CI Mirror: `./scripts/run_tests.sh`\n"
    )


def build_gemini_settings() -> str:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import gen_gemini_settings  # type: ignore
    return json.dumps(gen_gemini_settings.build(), indent=2, ensure_ascii=False) + "\n"


# ── Master Toolchain Compiler ─────────────────────────────────────────────────

def build_all_toolchains() -> dict[Path, str]:
    """Compile all toolchain targets into a dictionary of {relative_path: content}."""
    skills = load_skills()

    targets: dict[Path, str] = {}

    # 1. Cursor
    targets[Path(".cursor/rules/000-always-on.mdc")] = build_cursor_always_on()
    for prod in PRODUCTS:
        targets[Path(f".cursor/rules/product-{prod['id']}.mdc")] = build_cursor_product_rule(prod)
    targets[Path(".cursor/rules/agent-consultants.mdc")] = build_cursor_consultants()
    targets[Path(".cursorrules")] = build_cursorrules()

    # 2. Windsurf
    targets[Path(".windsurfrules")] = build_windsurfrules(skills)

    # 3. GitHub Copilot
    targets[Path(".github/copilot-instructions.md")] = build_copilot_instructions()

    # 4. Gemini CLI
    targets[Path(".gemini/settings.json")] = build_gemini_settings()

    return targets


# ── Synchronization Routines ──────────────────────────────────────────────────

def sync_single_symlink(target: Path, source: Path, verbose: bool = False) -> bool:
    """Ensure target is a symlink pointing to relative path of source."""
    rel_target = os.path.relpath(source, target.parent)
    if target.is_symlink():
        try:
            if os.readlink(target) == rel_target and target.exists():
                return True
        except OSError:
            pass
        target.unlink(missing_ok=True)
    elif target.exists() or os.path.lexists(target) or os.path.islink(target):
        remove_path(target)

    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() or os.path.lexists(target) or target.is_symlink():
        remove_path(target)
    is_dir = source.is_dir()
    os.symlink(rel_target, target, target_is_directory=is_dir)
    if verbose:
        print(f"  symlink: {target.relative_to(REPO)} -> {rel_target}")
    return True


def sync_single_copy_file(target: Path, source: Path, verbose: bool = False) -> bool:
    """Ensure target is a read-only copy of source."""
    if target.is_symlink():
        target.unlink(missing_ok=True)
    elif target.exists():
        if filecmp.cmp(source, target, shallow=False):
            make_readonly(target)
            return True
        make_writable(target)

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)
    make_readonly(target)
    if verbose:
        print(f"  copy file: {target.relative_to(REPO)}")
    return True


def sync_dir_copy(target_dir: Path, source_dir: Path, clean: bool = False, verbose: bool = False) -> bool:
    """Ensure target_dir contains read-only copies of source_dir."""
    if target_dir.is_symlink():
        target_dir.unlink(missing_ok=True)
    target_dir.mkdir(parents=True, exist_ok=True)

    source_files: set[Path] = set()
    for root, _, files in os.walk(source_dir):
        rel_root = Path(root).relative_to(source_dir)
        dest_root = target_dir / rel_root
        dest_root.mkdir(parents=True, exist_ok=True)
        for f in files:
            src_file = Path(root) / f
            dest_file = dest_root / f
            source_files.add(dest_file.resolve())
            sync_single_copy_file(dest_file, src_file, verbose=verbose)

    if clean:
        for root, _, files in os.walk(target_dir):
            for f in files:
                dest_file = Path(root) / f
                if dest_file.name == "DO_NOT_EDIT.md":
                    continue
                if dest_file.resolve() not in source_files:
                    make_writable(dest_file)
                    dest_file.unlink(missing_ok=True)
                    if verbose:
                        print(f"  pruned orphan: {dest_file.relative_to(REPO)}")

    return True


# ── Full Sync Engine ──────────────────────────────────────────────────────────

def run_sync(mode: str, clean: bool = False, verbose: bool = False) -> int:
    """Execute framework synchronization under specified mode."""
    print(f"Synchronizing AI Framework toolchains and mirrors (mode: {mode.upper()})...")

    # 1. Directory mirrors
    for target_rel, source_rel in DIR_MAPPINGS.items():
        target = REPO / target_rel
        source = REPO / source_rel
        if not source.exists():
            print(f"Warning: source '{source_rel}' does not exist, skipping.", file=sys.stderr)
            continue
        if mode == "symlink":
            sync_single_symlink(target, source, verbose=verbose)
        else:
            sync_dir_copy(target, source, clean=clean, verbose=verbose)

    # 2. Single-file mirrors (ROUTING.md)
    for target_rel, source_rel in FILE_MAPPINGS.items():
        target = REPO / target_rel
        source = REPO / source_rel
        if not source.exists():
            print(f"Warning: source '{source_rel}' does not exist, skipping.", file=sys.stderr)
            continue
        if mode == "symlink":
            sync_single_symlink(target, source, verbose=verbose)
        else:
            sync_single_copy_file(target, source, verbose=verbose)

    # 3. Gemini mirrors (.gemini/agents/ and .gemini/skills/)
    gemini_agents_dir = REPO / ".gemini" / "agents"
    gemini_skills_dir = REPO / ".gemini" / "skills"
    gemini_agents_dir.mkdir(parents=True, exist_ok=True)
    gemini_skills_dir.mkdir(parents=True, exist_ok=True)

    # Per-file agents
    for agent_src in sorted((AI / "agents").glob("*.md")):
        agent_dst = gemini_agents_dir / agent_src.name
        if mode == "symlink":
            sync_single_symlink(agent_dst, agent_src, verbose=verbose)
        else:
            sync_single_copy_file(agent_dst, agent_src, verbose=verbose)

    # Per-item skills
    for skill_src in sorted(p for p in (AI / "skills").iterdir() if p.is_dir()):
        skill_dst = gemini_skills_dir / skill_src.name
        if mode == "symlink":
            sync_single_symlink(skill_dst, skill_src, verbose=verbose)
        else:
            sync_dir_copy(skill_dst, skill_src, clean=clean, verbose=verbose)

    # 4. In copy mode, inject DO_NOT_EDIT.md banners; in symlink mode remove if present
    for parent_dir in (REPO / ".claude", REPO / ".agents", REPO / ".gemini"):
        banner_path = parent_dir / "DO_NOT_EDIT.md"
        if mode == "copy":
            if parent_dir.is_dir():
                if banner_path.is_symlink():
                    banner_path.unlink(missing_ok=True)
                else:
                    make_writable(banner_path)
                banner_path.write_text(DO_NOT_EDIT_BANNER, encoding="utf-8")
                make_readonly(banner_path)
        else:
            remove_path(banner_path)

    # 5. Multi-toolchain generation (Cursor, Windsurf, Copilot, Gemini settings)
    targets = build_all_toolchains()
    for rel_path, expected_content in targets.items():
        full_path = REPO / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        if full_path.exists():
            make_writable(full_path)
        full_path.write_text(expected_content, encoding="utf-8")
        if verbose:
            print(f"  generated: {rel_path}")

    # 6. Record .sync_mode metadata
    manifest = {
        "version": 1,
        "mode": mode,
        "synced_at": datetime.now(timezone.utc).isoformat(),
        "generator": "ai/skills/sync-framework/scripts/sync_framework.py",
        "trees": {
            **DIR_MAPPINGS,
            **FILE_MAPPINGS,
            ".gemini/agents": "ai/agents",
            ".gemini/skills": "ai/skills",
        },
    }
    SYNC_MODE_FILE.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Synchronized {len(targets)} toolchain files across Cursor, Windsurf, Copilot, and Gemini.")
    print(f"Framework mirrors synchronized: mode={mode} (.sync_mode updated).")
    return 0


# ── Check Routine ─────────────────────────────────────────────────────────────

def run_check(expected_mode: str | None = None, verbose: bool = False) -> int:
    """Verify that current framework trees and toolchains match expected sync state."""
    mode = expected_mode or get_current_sync_mode()
    drift: list[str] = []

    # 1. Check toolchain files
    targets = build_all_toolchains()
    for rel_path, expected_content in targets.items():
        full_path = REPO / rel_path
        if not full_path.exists():
            drift.append(f"{rel_path}: toolchain file missing")
        elif full_path.read_text(encoding="utf-8") != expected_content:
            drift.append(f"{rel_path}: content drift detected against canonical source")
        elif verbose:
            print(f"OK: {rel_path} in sync")

    # 2. Check directory mappings
    for target_rel, source_rel in DIR_MAPPINGS.items():
        target = REPO / target_rel
        source = REPO / source_rel
        if not target.exists() and not target.is_symlink():
            drift.append(f"{target_rel}: missing")
            continue
        if mode == "symlink":
            if not target.is_symlink():
                drift.append(f"{target_rel}: expected symlink, found real directory")
            elif not target.exists():
                drift.append(f"{target_rel}: broken symlink")
        else:
            if target.is_symlink():
                drift.append(f"{target_rel}: expected copy directory, found symlink")
            else:
                for root, _, files in os.walk(source):
                    rel = Path(root).relative_to(source)
                    for f in files:
                        t_file = target / rel / f
                        s_file = Path(root) / f
                        if not t_file.exists():
                            drift.append(f"{target_rel}/{rel}/{f}: missing copy file")
                        elif not filecmp.cmp(s_file, t_file, shallow=False):
                            drift.append(f"{target_rel}/{rel}/{f}: content mismatch with ai/")

    # 3. Check single-file mappings (ROUTING.md)
    for target_rel, source_rel in FILE_MAPPINGS.items():
        target = REPO / target_rel
        source = REPO / source_rel
        if not target.exists() and not target.is_symlink():
            drift.append(f"{target_rel}: missing")
            continue
        if mode == "symlink":
            if not target.is_symlink():
                drift.append(f"{target_rel}: expected symlink, found real file")
        else:
            if target.is_symlink():
                drift.append(f"{target_rel}: expected copy file, found symlink")
            elif not filecmp.cmp(source, target, shallow=False):
                drift.append(f"{target_rel}: content mismatch with {source_rel}")

    # 4. Check Gemini mirrors
    gemini_agents = REPO / ".gemini" / "agents"
    gemini_skills = REPO / ".gemini" / "skills"
    if not gemini_agents.is_dir():
        drift.append(".gemini/agents: missing directory")
    else:
        for p in (AI / "agents").glob("*.md"):
            dst = gemini_agents / p.name
            if mode == "symlink":
                if not dst.is_symlink() or not dst.exists():
                    drift.append(f".gemini/agents/{p.name}: missing or broken symlink")
            else:
                if not dst.exists() or not filecmp.cmp(p, dst, shallow=False):
                    drift.append(f".gemini/agents/{p.name}: missing or mismatched copy")

    if not gemini_skills.is_dir():
        drift.append(".gemini/skills: missing directory")
    else:
        for p in (AI / "skills").iterdir():
            if not p.is_dir() or p.name.startswith("."):
                continue
            dst = gemini_skills / p.name
            if mode == "symlink":
                if not dst.is_symlink() or not dst.exists():
                    drift.append(f".gemini/skills/{p.name}: missing or broken symlink")
            else:
                if not dst.is_dir():
                    drift.append(f".gemini/skills/{p.name}: missing copy directory")

    if drift:
        print(f"DRIFT DETECTED ({len(drift)} issues):", file=sys.stderr)
        for issue in drift:
            print(f"  - {issue}", file=sys.stderr)
        print("Run: python3 ai/skills/sync-framework/scripts/sync_framework.py", file=sys.stderr)
        return 1

    print(f"OK: All toolchains and mirrors are 100% in sync (mode={mode})")
    return 0


# ── Entrypoint ────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--mode",
        choices=["auto", "symlink", "copy"],
        default="auto",
        help="Synchronization mode (default: auto)",
    )
    parser.add_argument("--copy", action="store_true", help="Alias for --mode=copy")
    parser.add_argument("--check", action="store_true", help="Check sync state and exit 1 on drift")
    parser.add_argument("--clean", action="store_true", help="Remove orphaned files in target directories")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    args = parser.parse_args()

    target_mode = "copy" if args.copy else args.mode

    if args.check:
        expected = None if target_mode == "auto" else target_mode
        return run_check(expected_mode=expected, verbose=args.verbose)

    if target_mode == "auto":
        can_symlink = probe_symlink_capability(REPO)
        if can_symlink:
            target_mode = "symlink"
        else:
            print("Notice: Symlink creation not permitted or unsupported in this environment.")
            print("        Falling back to non-symlink COPY mode.")
            target_mode = "copy"

    return run_sync(mode=target_mode, clean=args.clean, verbose=args.verbose)


if __name__ == "__main__":
    sys.exit(main())
